import type { SaleMode } from './types';

export const PHASE2_BATCH_ID = 'phase2-2026-08-28';
export const PHASE2_BATCH_NAME = 'Fotos Leaving PY · 28 de agosto de 2026';

export type Phase2BatchItem = {
  id: string;
  itemNumber: number;
  title: string;
  category: string;
  description: string;
  condition: string;
  conditionNotes: string;
  knownDefects: string;
  photos: string[];
  asking: number;
  marketLow: number;
  marketHigh: number;
  fast: number;
  floor: number;
  confidence: 'Alta' | 'Media' | 'Baja';
  saleMode: SaleMode;
  pickupDate: string | null;
  pickupWindowStart: string | null;
  pickupWindowEnd: string | null;
  includedAccessories?: string[];
  sellerConfirmedFields?: string[];
  requiresVehicle?: boolean;
  requiresLoadingHelp?: boolean;
  flag?: string;
  research: string;
};

const immediate = { saleMode: 'IMMEDIATE' as const, pickupDate: null, pickupWindowStart: null, pickupWindowEnd: null };
const delayed = { saleMode: 'DELAYED' as const, pickupDate: '2026-12-09', pickupWindowStart: '2026-12-09', pickupWindowEnd: '2026-12-12' };

const SOURCES = {
  office: 'Clasipar, silla ergonómica nueva Gs. 650.000 (16/02/2026) y silla de escritorio usada Gs. 150.000 (04/08/2026). https://clasipar.paraguay.com/herramientas-de-construccion-y-oficina/muebles-para-negocios-y-oficinas/silla-giratoria-ergonomica-sillon-giratorio-ergonomico-1388096 | https://clasipar.paraguay.com/hobbies-musica-arte-y-libros/arte-antiguedades/vendo-silla-para-escritorio-sillas-mueble-metalico-archivero-camitas-63776',
  dispenser: 'Clasipar, dispensers nuevos comparables Gs. 899.000–1.400.000 (08/01/2026 y 20/11/2025). https://clasipar.paraguay.com/hogar-muebles-y-jardin/electrodomesticos-para-la-cocina/bebedero-consumer-de-mesa-simple-dispenser-de-agua-friocaliente-4359-1951114 | https://clasipar.paraguay.com/hogar-muebles-y-jardin/otros-en-hogar-muebles-y-jardin/bebedero-consumer-de-pie-con-heladera-dispenser-de-agua-friocaliente-1326-1997066',
  decor: 'Clasipar, cuadros decorativos usados/publicados entre Gs. 70.000 y 100.000 (marzo–mayo 2026). https://clasipar.paraguay.com/hogar-muebles-y-jardin/decoracion-para-el-hogar/vendo-cuadros-2505136 | https://clasipar.paraguay.com/hogar-muebles-y-jardin/decoracion-para-el-hogar/vendo-cuadritos-varios-2745413',
  furniture: 'Clasipar, estantes y bibliotecas usados Gs. 400.000–1.500.000 (junio–agosto 2026). https://clasipar.paraguay.com/hobbies-musica-arte-y-libros/arte-antiguedades/estante-y-mueble-tipo-biblioteca-vendo-63081 | https://clasipar.paraguay.com/hobbies-musica-arte-y-libros/arte-antiguedades/vendo-biblioteca-antigua-grande-color-oscuro-1220699',
  desk: 'Clasipar, mesa para computadora nueva Gs. 450.000 (21/08/2026) y escritorio con silla usado Gs. 300.000 (19/06/2026). https://clasipar.paraguay.com/hogar-muebles-y-jardin/muebles-para-el-hogar/mesa-para-computadora-46947 | https://clasipar.paraguay.com/hobbies-musica-arte-y-libros/arte-antiguedades/vendo-escritorio-con-su-silla-1946316',
  blender: 'Estimación por depreciación de licuadoras Oster de vaso de vidrio disponibles localmente; se requiere confirmar funcionamiento. Investigación: 29/08/2026.',
  transformer: 'Clasipar, transformadores 110/220 V de 500 W a 3000 W desde Gs. 150.000 (13/07/2026); ajuste por unidad 3000 VA y estado usado. https://clasipar.paraguay.com/electronica/otros-electronica/transformador-de-220-a-110v-para-equipos-americanos-brasileros-canadienses-o-japoneses-110-1227594',
  grill: 'Clasipar, parrillas nuevas con ruedas Gs. 1.990.000–2.300.000 (febrero–agosto 2026); aplicado descuento por uso y estado visual. https://clasipar.paraguay.com/hogar-muebles-y-jardin/electrodomesticos-para-la-cocina/parrilla-para-asado-inoxidable-de-75x45cm-gastronomica-carbonera-de-planchuela-2481029 | https://clasipar.paraguay.com/hogar-muebles-y-jardin/electrodomesticos-para-la-cocina/parrilla-con-sistema-sube-y-baja-2857539',
  tools: 'Referencias minoristas Paraguay: hacha Tramontina Gs. 73.400 y pala Tramontina Gs. 63.950; precios usados ajustados por desgaste. https://www.tiendalincoln.com.py/shop/product/hacha-caza-tramontina-40562600g-914088.html/ref%3Dc%3A728 | https://fortis.com.py/categoria/casa-and-jardin?page=20',
  chairs: 'La Norteña, silla plástica blanca nueva Gs. 80.000; lote usado ajustado por cantidad y estado. https://lanortena.net.py/prod-category/silla/',
  speaker: 'Clasipar, parlante Kolke de 15 pulgadas con accesorios y trípode Gs. 1.750.000 nuevo (22/08/2026); aplicado descuento por uso y accesorios no confirmados. https://clasipar.paraguay.com/electronica/tv-audio-video/parlante-inalambrico-kolke-woofer-15-120-tweeter-3-80-2450201',
  plants: 'Comparable local de vivero: planta en maceta Gs. 150.000 (19/08/2026); ajuste por especie, tamaño, maceta y soporte visibles. https://clasipar.paraguay.com/hogar-muebles-y-jardin/otros-en-hogar-muebles-y-jardin/planta-de-coco-brasileno-enano-2041362',
  gas: 'Referencia local de precio: garrafa completa de 13 kg Gs. 440.000. El estado funcional y el contenido fueron aclarados por el vendedor; la fecha del envase no bloquea esta revisión. https://www.guiadeleste.com.py/empresas/gas_a_domicilio/',
  general: 'Estimación por comparables locales de hogar y descuento por venta particular. Investigación: 29/08/2026.',
  mop: 'Fortis, Mopa Línea Bella nueva Gs. 30.900; precio reducido por tratarse de un artículo usado en venta particular. https://www.fortis.com.py/categoria/casa-and-jardin/accesorios-de-limpieza',
  table: 'Clasipar, mesas auxiliares publicadas entre Gs. 100.000 y 480.000 (agosto de 2026); ajuste por madera usada, tamaño y estado visual. https://clasipar.paraguay.com/hogar-muebles-y-jardin/accesorios-de-mesa-y-cocina/mesa-plegable-de-madera-super-oferta-1994770 | https://clasipar.paraguay.com/hogar-muebles-y-jardin/muebles-para-el-hogar/mesa-auxiliar-1938427',
};

function item(n: number, data: Omit<Phase2BatchItem, 'id' | 'itemNumber'>): Phase2BatchItem {
  return { id: `real-20260828-${String(n).padStart(2, '0')}`, itemNumber: n, ...data };
}

export const PHASE2_BATCH_ITEMS: Phase2BatchItem[] = [
  item(1, { title: 'Silla ergonómica de oficina con apoyacabeza', category: 'Oficina', description: 'Silla giratoria negra con respaldo de malla, apoyacabeza, apoyabrazos regulables y base con ruedas.', condition: 'Buen estado visual', conditionNotes: 'Presenta polvo y señales normales de uso en asiento y respaldo.', knownDefects: 'Funcionamiento de ajustes y pistón a confirmar.', photos: ['796d7925-6c94-44ab-a56d-40b527702c7c.jpg'], asking: 420000, marketLow: 300000, marketHigh: 650000, fast: 350000, floor: 300000, confidence: 'Media', ...delayed, requiresVehicle: true, research: SOURCES.office }),
  item(2, { title: 'Dispenser de agua JAM con 4 bidones', category: 'Electrodomésticos', description: 'El agua fría funciona muy bien. La función de agua caliente no funciona. Incluye 4 bidones usados.', condition: 'Usado y parcialmente funcional', conditionNotes: 'El vendedor confirma que el agua fría funciona muy bien; la carcasa presenta señales normales de uso.', knownDefects: 'La función de agua caliente no funciona.', photos: ['a78ba12f-2a2e-4b08-9485-f9300870a8fe Copy.JPG'], asking: 450000, marketLow: 350000, marketHigh: 700000, fast: 380000, floor: 300000, confidence: 'Media', ...delayed, requiresVehicle: true, includedAccessories: ['4 bidones grandes usados'], sellerConfirmedFields: ['description', 'condition', 'conditionNotes', 'knownDefects', 'includedAccessories'], research: SOURCES.dispenser }),
  item(3, { title: 'Bolso tejido de fibras naturales', category: 'Hogar', description: 'Bolso amplio tejido en tono natural, con asas largas y detalles oscuros.', condition: 'Buen estado visual', conditionNotes: 'No se observan roturas en la foto.', knownDefects: 'Interior y resistencia de las asas no verificados.', photos: ['IMG_7654.JPG'], asking: 80000, marketLow: 60000, marketHigh: 120000, fast: 60000, floor: 50000, confidence: 'Media', ...immediate, research: SOURCES.general }),
  item(4, { title: 'Cuadro floral en tonos violetas', category: 'Decoración', description: 'Cuadro decorativo con flores violetas sobre fondo claro.', condition: 'Buen estado visual', conditionNotes: 'Marco y superficie sin daños evidentes.', knownDefects: 'Medidas no disponibles.', photos: ['IMG_7677.JPG'], asking: 90000, marketLow: 70000, marketHigh: 130000, fast: 70000, floor: 60000, confidence: 'Media', ...immediate, research: SOURCES.decor }),
  item(5, { title: 'Estante plástico blanco de 3 niveles', category: 'Muebles', description: 'Estante liviano de plástico blanco con tres niveles abiertos.', condition: 'Usado', conditionNotes: 'Se observan marcas leves de uso.', knownDefects: 'Estabilidad y medidas a confirmar.', photos: ['IMG_7678.JPG'], asking: 80000, marketLow: 60000, marketHigh: 120000, fast: 65000, floor: 50000, confidence: 'Media', ...immediate, research: SOURCES.general }),
  item(6, { title: 'Cuadro decorativo de ave', category: 'Decoración', description: 'Cuadro vertical con ilustración de un ave entre ramas.', condition: 'Buen estado visual', conditionNotes: 'Sin daños evidentes en la foto.', knownDefects: 'Medidas no disponibles.', photos: ['IMG_7679.JPG'], asking: 90000, marketLow: 70000, marketHigh: 130000, fast: 70000, floor: 60000, confidence: 'Media', ...immediate, research: SOURCES.decor }),
  item(7, { title: 'Cuadro “Spread Your Love”', category: 'Decoración', description: 'Lámina decorativa tipográfica con la frase “Spread Your Love”.', condition: 'Buen estado visual', conditionNotes: 'Marco y frente sin daños evidentes.', knownDefects: 'Medidas no disponibles.', photos: ['IMG_7682.JPG'], asking: 70000, marketLow: 50000, marketHigh: 100000, fast: 55000, floor: 45000, confidence: 'Media', ...immediate, research: SOURCES.decor }),
  item(8, { title: 'Perchero decorativo de pared', category: 'Decoración', description: 'Perchero de pared con base decorativa y varios ganchos metálicos.', condition: 'Buen estado visual', conditionNotes: 'Se observan señales leves de uso.', knownDefects: 'Tornillos de instalación no confirmados.', photos: ['IMG_7683.JPG'], asking: 70000, marketLow: 50000, marketHigh: 100000, fast: 55000, floor: 45000, confidence: 'Media', ...immediate, research: SOURCES.general }),
  item(9, { title: 'Paraguas bordó con mango de madera', category: 'Hogar', description: 'Paraguas bordó de uso personal con mango curvo de madera. Se vende de forma individual.', condition: 'Usado', conditionNotes: 'Tela, varillas y mecanismo requieren revisión individual del vendedor.', knownDefects: 'No se observan roturas evidentes en la foto cerrada.', photos: ['IMG_7684.JPG'], asking: 50000, marketLow: 35000, marketHigh: 80000, fast: 40000, floor: 30000, confidence: 'Media', ...immediate, research: SOURCES.general }),
  item(10, { title: 'Cajonera angosta de madera rústica', category: 'Muebles', description: 'Mueble alto y angosto de madera con varios cajones y acabado rústico.', condition: 'Buen estado visual', conditionNotes: 'Desgaste coherente con el estilo y el uso.', knownDefects: 'Deslizamiento de cajones y medidas a confirmar.', photos: ['IMG_7686.JPG', 'IMG_7689.JPG'], asking: 450000, marketLow: 350000, marketHigh: 650000, fast: 380000, floor: 320000, confidence: 'Media', ...delayed, requiresVehicle: true, research: SOURCES.furniture }),
  item(11, { title: 'Sillón individual beige con almohadón', category: 'Muebles', description: 'Sillón tapizado beige de un cuerpo, con brazos y almohadón violeta incluido.', condition: 'Buen estado visual', conditionNotes: 'Tapizado con señales leves de uso.', knownDefects: 'Firmeza del asiento y medidas a confirmar.', photos: ['IMG_7690.JPG'], asking: 650000, marketLow: 500000, marketHigh: 900000, fast: 550000, floor: 450000, confidence: 'Media', ...delayed, requiresVehicle: true, requiresLoadingHelp: true, research: 'Investigación específica pendiente para este sillón tapizado. La referencia anterior de estantes y bibliotecas no corresponde a este artículo.' }),
  item(12, { title: 'Felpudo “hello”', category: 'Hogar', description: 'Felpudo rectangular de entrada con la palabra “hello”.', condition: 'Usado', conditionNotes: 'Desgaste visible propio del uso exterior.', knownDefects: 'Medidas no disponibles.', photos: ['IMG_7691.JPG'], asking: 50000, marketLow: 35000, marketHigh: 70000, fast: 40000, floor: 30000, confidence: 'Media', ...immediate, research: SOURCES.general }),
  item(13, { title: 'Potus con maceta', category: 'Jardín', description: 'Planta de potus frondosa en maceta, lista para interior o galería.', condition: 'Buen estado visual', conditionNotes: 'Follaje verde y abundante en la foto.', knownDefects: 'Estado de raíces no verificado.', photos: ['IMG_7692.JPG'], asking: 120000, marketLow: 90000, marketHigh: 170000, fast: 100000, floor: 80000, confidence: 'Media', ...immediate, research: SOURCES.plants }),
  item(14, { title: 'Sansevieria con maceta', category: 'Jardín', description: 'Sansevieria de hojas altas en maceta decorativa.', condition: 'Buen estado visual', conditionNotes: 'Hojas firmes con pequeñas marcas naturales.', knownDefects: 'Estado de raíces no verificado.', photos: ['IMG_7693.JPG'], asking: 150000, marketLow: 110000, marketHigh: 220000, fast: 125000, floor: 100000, confidence: 'Media', ...immediate, research: SOURCES.plants }),
  item(15, { title: 'Regadera turquesa', category: 'Jardín', description: 'Regadera plástica turquesa con asa superior y pico largo.', condition: 'Usado', conditionNotes: 'Presenta señales leves de uso.', knownDefects: 'Capacidad y posibles pérdidas no verificadas.', photos: ['IMG_7695.JPG'], asking: 60000, marketLow: 45000, marketHigh: 85000, fast: 50000, floor: 40000, confidence: 'Media', ...immediate, research: SOURCES.general }),
  item(16, { title: 'Varas decorativas con florero', category: 'Decoración', description: 'Conjunto de varas naturales decorativas en florero de piso.', condition: 'Buen estado visual', conditionNotes: 'Conjunto completo según la foto.', knownDefects: 'Medidas no disponibles.', photos: ['IMG_7697.JPG'], asking: 120000, marketLow: 90000, marketHigh: 180000, fast: 100000, floor: 80000, confidence: 'Media', ...immediate, research: SOURCES.general }),
  item(17, { title: 'Licuadora Oster de vaso de vidrio', category: 'Electrodomésticos', description: 'Licuadora Oster negra con vaso de vidrio de 6 tazas y control de 8 velocidades; base “All Metal Drive”. Funciona muy bien y tuvo poco uso.', condition: 'Muy buen estado', conditionNotes: 'El vendedor confirma que funciona muy bien y que tuvo poco uso.', knownDefects: 'Sin defectos conocidos informados por el vendedor.', photos: ['IMG_7698.JPG'], asking: 280000, marketLow: 220000, marketHigh: 400000, fast: 240000, floor: 200000, confidence: 'Media', ...delayed, includedAccessories: ['Vaso de vidrio', 'Tapa'], sellerConfirmedFields: ['description', 'condition', 'conditionNotes', 'knownDefects'], research: SOURCES.blender }),
  item(18, { title: 'Transformador elevador/reductor 3000 VA', category: 'Electrónica', description: 'Transformador step up & down para 110/120 V y 220/240 V, potencia indicada de 3000 VA máximo. El vendedor confirma que funciona correctamente y es plenamente funcional.', condition: 'Buen estado y funcional', conditionNotes: 'Carcasa y conexiones presentes; etiqueta legible. Funcionamiento correcto confirmado por el vendedor.', knownDefects: 'Sin defectos funcionales conocidos informados por el vendedor.', photos: ['IMG_7700.JPG'], asking: 400000, marketLow: 300000, marketHigh: 550000, fast: 350000, floor: 300000, confidence: 'Media', ...delayed, sellerConfirmedFields: ['description', 'condition', 'conditionNotes', 'knownDefects'], research: SOURCES.transformer }),
  item(19, { title: 'Juego de canastos tejidos', category: 'Hogar', description: 'Conjunto de canastos y bandejas tejidos en fibras naturales, de distintos tamaños.', condition: 'Buen estado visual', conditionNotes: 'No se observan roturas importantes.', knownDefects: 'Cantidad exacta y medidas a confirmar.', photos: ['IMG_7702.JPG'], asking: 100000, marketLow: 80000, marketHigh: 150000, fast: 85000, floor: 70000, confidence: 'Media', ...immediate, research: SOURCES.general }),
  item(20, { title: 'Arreglo floral artificial en florero azul', category: 'Decoración', description: 'Arreglo de flores artificiales claras en florero de vidrio azul.', condition: 'Buen estado visual', conditionNotes: 'Conjunto completo según la foto.', knownDefects: 'Sin defectos visibles relevantes.', photos: ['IMG_7706.JPG'], asking: 100000, marketLow: 70000, marketHigh: 140000, fast: 80000, floor: 65000, confidence: 'Media', ...immediate, research: SOURCES.general }),
  item(21, { title: 'Florero de terracota', category: 'Decoración', description: 'Florero alto de terracota en tono natural.', condition: 'Buen estado visual', conditionNotes: 'No se observan grietas evidentes.', knownDefects: 'Medidas no disponibles.', photos: ['IMG_7707.JPG'], asking: 80000, marketLow: 60000, marketHigh: 120000, fast: 65000, floor: 50000, confidence: 'Media', ...immediate, research: SOURCES.general }),
  item(22, { title: 'Garrafa Copesa Gas de 13 kg con regulador', category: 'Cocina', description: 'Garrafa Copesa Gas de 13 kg vacía, funciona correctamente y está lista para recarga o canje. No incluye gas.', condition: 'Usado y funcional', conditionNotes: 'Pintura con desgaste y marcas de uso. El vendedor confirma que está vacía y funciona correctamente.', knownDefects: 'Sin defectos funcionales conocidos informados por el vendedor.', photos: ['IMG_7708.JPG'], asking: 250000, marketLow: 180000, marketHigh: 320000, fast: 210000, floor: 180000, confidence: 'Media', ...delayed, includedAccessories: ['Regulador Imar', 'Manguera', 'Abrazadera'], sellerConfirmedFields: ['description', 'condition', 'conditionNotes', 'knownDefects', 'includedAccessories'], research: SOURCES.gas }),
  item(23, { title: 'Garrafa Gastotal de 13 kg', category: 'Cocina', description: 'Garrafa verde Gastotal de 13 kg en uso hasta noviembre. Se espera que pueda contener algo de gas al venderse, pero la cantidad restante dependerá del uso y no puede conocerse ni garantizarse de antemano.', condition: 'Usado y funcional', conditionNotes: 'Pintura con desgaste y puntos de óxido superficial visibles. El contenido restante dependerá del uso hasta el retiro.', knownDefects: 'No se garantiza una cantidad de gas. No se exige una fecha de inspección o habilitación sin una marca claramente relevante.', photos: ['IMG_7709.JPG'], asking: 220000, marketLow: 160000, marketHigh: 300000, fast: 190000, floor: 160000, confidence: 'Media', ...delayed, sellerConfirmedFields: ['description', 'conditionNotes', 'knownDefects'], research: SOURCES.gas }),
  item(24, { title: 'Drácena con maceta', category: 'Jardín', description: 'Planta tipo drácena de porte medio en maceta.', condition: 'Buen estado visual', conditionNotes: 'Follaje verde con señales naturales.', knownDefects: 'Estado de raíces no verificado.', photos: ['IMG_7710.JPG'], asking: 160000, marketLow: 120000, marketHigh: 240000, fast: 135000, floor: 110000, confidence: 'Media', ...immediate, research: SOURCES.plants }),
  item(25, { title: 'Reloj de pared decorativo de café', category: 'Decoración', description: 'Reloj de pared redondo con diseño temático de café.', condition: 'Buen estado visual', conditionNotes: 'Frente sin daños evidentes.', knownDefects: 'Movimiento y precisión no verificados.', photos: ['IMG_7714.JPG'], asking: 80000, marketLow: 60000, marketHigh: 120000, fast: 65000, floor: 50000, confidence: 'Media', ...immediate, research: SOURCES.general }),
  item(26, { title: 'Planta de jade con maceta', category: 'Jardín', description: 'Planta de jade de porte medio en maceta.', condition: 'Buen estado visual', conditionNotes: 'Hojas carnosas y verdes.', knownDefects: 'Estado de raíces no verificado.', photos: ['IMG_7716.JPG'], asking: 120000, marketLow: 90000, marketHigh: 180000, fast: 100000, floor: 80000, confidence: 'Media', ...immediate, research: SOURCES.plants }),
  item(27, { title: 'Cinta con maceta', category: 'Jardín', description: 'Planta cinta o lazo de amor en maceta.', condition: 'Buen estado visual', conditionNotes: 'Follaje abundante.', knownDefects: 'Estado de raíces no verificado.', photos: ['IMG_7718.JPG'], asking: 100000, marketLow: 75000, marketHigh: 150000, fast: 85000, floor: 70000, confidence: 'Media', ...immediate, research: SOURCES.plants }),
  item(28, { title: 'Helecho con maceta y soporte de madera', category: 'Jardín', description: 'Helecho frondoso en maceta, con soporte bajo de madera incluido.', condition: 'Buen estado visual', conditionNotes: 'Follaje abundante y soporte sin daños evidentes.', knownDefects: 'Estado de raíces no verificado.', photos: ['IMG_7719.JPG'], asking: 200000, marketLow: 150000, marketHigh: 280000, fast: 170000, floor: 140000, confidence: 'Media', ...immediate, research: SOURCES.plants }),
  item(29, { title: 'Planta aromática con maceta y soporte', category: 'Jardín', description: 'Planta de aspecto aromático o arbustivo en maceta, con soporte metálico.', condition: 'Buen estado visual', conditionNotes: 'Follaje verde; especie exacta no confirmada.', knownDefects: 'Especie y estado de raíces a confirmar.', photos: ['IMG_7721.JPG'], asking: 150000, marketLow: 110000, marketHigh: 220000, fast: 125000, floor: 100000, confidence: 'Baja', ...immediate, research: SOURCES.plants }),
  item(30, { title: 'Jardinera rectangular', category: 'Jardín', description: 'Jardinera rectangular vacía, apta para exterior o galería.', condition: 'Usado', conditionNotes: 'Presenta tierra y señales de uso.', knownDefects: 'Drenaje y medidas a confirmar.', photos: ['IMG_7722.JPG'], asking: 120000, marketLow: 90000, marketHigh: 180000, fast: 100000, floor: 80000, confidence: 'Media', ...immediate, research: SOURCES.general }),
  item(31, { title: 'Tradescantia morada con maceta y soporte', category: 'Jardín', description: 'Planta de follaje morado en maceta, con soporte de madera incluido.', condition: 'Buen estado visual', conditionNotes: 'Dos vistas del mismo conjunto; follaje abundante.', knownDefects: 'Estado de raíces no verificado.', photos: ['IMG_7723.JPG', 'IMG_7729.JPG'], asking: 170000, marketLow: 130000, marketHigh: 240000, fast: 145000, floor: 120000, confidence: 'Media', ...immediate, research: SOURCES.plants }),
  item(32, { title: 'Pala de jardín', category: 'Herramientas', description: 'Pala de punta con mango largo para jardín o patio.', condition: 'Usado', conditionNotes: 'Tiene tierra y desgaste propio del uso.', knownDefects: 'Unión entre mango y hoja no verificada en detalle.', photos: ['IMG_7724.JPG'], asking: 50000, marketLow: 35000, marketHigh: 65000, fast: 40000, floor: 30000, confidence: 'Alta', ...immediate, research: SOURCES.tools }),
  item(33, { title: 'Lote de 3 plantas pequeñas con macetas', category: 'Jardín', description: 'Lote de tres plantas pequeñas con sus macetas, incluida una aloe. La mesa que aparece en las fotos no está incluida. Se vende por separado.', condition: 'Buen estado visual', conditionNotes: 'Incluye las tres plantas y sus recipientes visibles.', knownDefects: 'Estado de raíces no verificado.', photos: ['IMG_7725.JPG'], asking: 200000, marketLow: 150000, marketHigh: 300000, fast: 170000, floor: 140000, confidence: 'Media', ...immediate, includedAccessories: ['3 macetas o recipientes visibles'], sellerConfirmedFields: ['description', 'includedAccessories'], research: SOURCES.plants }),
  item(34, { title: 'Parrilla a carbón Fire King con ruedas', category: 'Cocina', description: 'Parrilla Fire King a carbón con tapa, termómetro, bandejas laterales, estante inferior y ruedas.', condition: 'Buen estado usado', conditionNotes: 'Tres vistas muestran exterior, interior y funda protectora.', knownDefects: 'Desgaste y residuos normales de cocción; accesorios internos a confirmar.', photos: ['IMG_7726.JPG', 'IMG_7727.JPG', 'IMG_7745.JPG'], asking: 950000, marketLow: 750000, marketHigh: 1300000, fast: 800000, floor: 700000, confidence: 'Media', ...delayed, requiresVehicle: true, requiresLoadingHelp: true, research: SOURCES.grill }),
  item(35, { title: 'Planta de jade grande con maceta', category: 'Jardín', description: 'Planta de jade de mayor tamaño en maceta, fotografiada desde dos ángulos.', condition: 'Buen estado visual', conditionNotes: 'Follaje abundante y sano en las fotos.', knownDefects: 'Estado de raíces no verificado.', photos: ['IMG_7730.JPG', 'IMG_7732.JPG'], asking: 150000, marketLow: 110000, marketHigh: 220000, fast: 125000, floor: 100000, confidence: 'Media', ...immediate, research: SOURCES.plants }),
  item(36, { title: 'Maceta grande blanca acanalada', category: 'Jardín', description: 'Maceta grande blanca con acabado acanalado vertical.', condition: 'Buen estado visual', conditionNotes: 'No se observan grietas evidentes.', knownDefects: 'Medidas y drenaje a confirmar.', photos: ['IMG_7733.JPG'], asking: 150000, marketLow: 110000, marketHigh: 220000, fast: 125000, floor: 100000, confidence: 'Media', ...immediate, research: SOURCES.general }),
  item(37, { title: 'Hacha Tramontina de mango largo', category: 'Herramientas', description: 'Hacha Tramontina con mango de madera para tareas de jardín y corte.', condition: 'Usado', conditionNotes: 'Hoja y mango presentan desgaste de uso.', knownDefects: 'Filo y fijación de la cabeza a revisar antes de usar.', photos: ['IMG_7734.JPG'], asking: 50000, marketLow: 40000, marketHigh: 70000, fast: 45000, floor: 35000, confidence: 'Alta', ...immediate, research: SOURCES.tools }),
  item(38, { title: 'Tijera cortacerco', category: 'Herramientas', description: 'Tijera manual de hojas largas y mangos de madera para cercos y arbustos.', condition: 'Usado', conditionNotes: 'Presenta desgaste y suciedad propios del uso.', knownDefects: 'Filo y ajuste del perno a confirmar.', photos: ['IMG_7735.JPG'], asking: 50000, marketLow: 40000, marketHigh: 80000, fast: 45000, floor: 35000, confidence: 'Media', ...immediate, research: SOURCES.tools }),
  item(39, { title: 'Tijera de poda de mango largo Fascy', category: 'Herramientas', description: 'Tijera de poda Fascy con mangos largos amarillos y sistema de palanca.', condition: 'Buen estado visual', conditionNotes: 'Etiqueta y mecanismo visibles.', knownDefects: 'Filo y ajuste del mecanismo a confirmar.', photos: ['IMG_7736.JPG'], asking: 100000, marketLow: 80000, marketHigh: 150000, fast: 85000, floor: 70000, confidence: 'Media', ...immediate, research: SOURCES.tools }),
  item(40, { title: 'Mopa completa', category: 'Hogar', description: 'Mopa completa con mango metálico y cabezal para limpiar pisos. Se vende completa, tal como aparece en la foto.', condition: 'Usada', conditionNotes: 'El mango y el cabezal están presentes. Se observan señales normales de uso.', knownDefects: 'No se han informado defectos funcionales específicos; se vende en el estado mostrado en la foto.', photos: ['IMG_7737.JPG'], asking: 20000, marketLow: 15000, marketHigh: 30000, fast: 18000, floor: 15000, confidence: 'Media', ...immediate, includedAccessories: ['Mango metálico', 'Cabezal de mopa'], sellerConfirmedFields: ['title', 'description', 'condition', 'conditionNotes', 'knownDefects', 'askingPricePYG', 'includedAccessories'], research: SOURCES.mop }),
  item(41, { title: 'Juego de 4 sillas plásticas blancas', category: 'Muebles', description: 'Lote de cuatro sillas plásticas blancas con brazos, aptas para patio o uso interior.', condition: 'Usado', conditionNotes: 'Presentan marcas y suciedad leves de uso exterior.', knownDefects: 'Estabilidad y fisuras pequeñas a confirmar.', photos: ['IMG_7739.JPG'], asking: 180000, marketLow: 140000, marketHigh: 240000, fast: 150000, floor: 120000, confidence: 'Alta', ...immediate, requiresVehicle: true, research: SOURCES.chairs }),
  item(42, { title: 'Basurero exterior con tapa y ruedas', category: 'Hogar', description: 'Basurero grande para exterior con tapa y ruedas.', condition: 'Usado', conditionNotes: 'Presenta señales normales de uso exterior.', knownDefects: 'Capacidad, cierre de tapa y ruedas a confirmar.', photos: ['IMG_7740.JPG'], asking: 200000, marketLow: 150000, marketHigh: 300000, fast: 170000, floor: 140000, confidence: 'Media', ...immediate, requiresVehicle: true, research: SOURCES.general }),
  item(43, { title: 'Pala recogedora metálica', category: 'Hogar', description: 'Pala recogedora metálica con mango corto.', condition: 'Usado', conditionNotes: 'Desgaste visible propio del uso.', knownDefects: 'Sin defectos relevantes visibles.', photos: ['IMG_7743.JPG'], asking: 30000, marketLow: 20000, marketHigh: 45000, fast: 25000, floor: 20000, confidence: 'Alta', ...immediate, research: SOURCES.general }),
  item(44, { title: 'Mesa auxiliar plegable', category: 'Muebles', description: 'Mesa auxiliar plegable de estructura oscura y superficie rectangular, fotografiada abierta y cerrada.', condition: 'Buen estado visual', conditionNotes: 'Tres vistas del mismo artículo.', knownDefects: 'Medidas y firmeza del mecanismo a confirmar.', photos: ['IMG_7747.JPG', 'IMG_7751.JPG', 'IMG_7753.JPG'], asking: 220000, marketLow: 170000, marketHigh: 320000, fast: 185000, floor: 150000, confidence: 'Media', ...immediate, requiresVehicle: true, research: SOURCES.general }),
  item(45, { title: 'Sillón individual marrón oscuro', category: 'Muebles', description: 'Sillón tapizado marrón oscuro de un cuerpo, con brazos anchos.', condition: 'Buen estado visual', conditionNotes: 'Dos fotos muestran el mismo sillón; tapizado con señales leves de uso.', knownDefects: 'Firmeza del asiento y medidas a confirmar.', photos: ['IMG_7748.JPG', 'IMG_7750.JPG'], asking: 650000, marketLow: 500000, marketHigh: 900000, fast: 550000, floor: 450000, confidence: 'Media', ...delayed, requiresVehicle: true, requiresLoadingHelp: true, research: 'Investigación específica pendiente para este sillón tapizado. La referencia anterior de estantes y bibliotecas no corresponde a este artículo.' }),
  item(46, { title: 'Gabinete angosto negro con puerta tejida', category: 'Muebles', description: 'Gabinete alto y angosto negro, con puerta frontal de tejido tipo ratán y estantes interiores.', condition: 'Buen estado visual', conditionNotes: 'Dos vistas muestran frente e interior.', knownDefects: 'Medidas y herrajes a confirmar.', photos: ['IMG_7755.JPG', 'IMG_7756.JPG'], asking: 400000, marketLow: 300000, marketHigh: 550000, fast: 340000, floor: 280000, confidence: 'Media', ...delayed, requiresVehicle: true, research: SOURCES.furniture }),
  item(47, { title: 'Juego de 3 repisas flotantes', category: 'Muebles', description: 'Conjunto de tres repisas de pared en tono oscuro, con soportes y ganchos inferiores.', condition: 'Buen estado visual', conditionNotes: 'Se muestran las tres piezas juntas.', knownDefects: 'Tornillos y tarugos de instalación no confirmados.', photos: ['IMG_7765.JPG'], asking: 180000, marketLow: 140000, marketHigh: 260000, fast: 150000, floor: 120000, confidence: 'Media', ...immediate, research: SOURCES.general }),
  item(48, { title: 'Parlante Kolke con 2 micrófonos y trípode', category: 'Electrónica', description: 'Parlante amplificado Kolke usado y funcional. Incluye dos micrófonos inalámbricos, sus soportes y un trípode firme de altura regulable.', condition: 'Usado y funcional', conditionNotes: 'El vendedor confirma que funciona. Gabinete, trípode y cable presentan señales normales de uso.', knownDefects: 'Modelo y potencia exactos no confirmados; no se inventan especificaciones técnicas.', photos: ['IMG_7777.JPG'], asking: 850000, marketLow: 650000, marketHigh: 1100000, fast: 750000, floor: 650000, confidence: 'Media', ...delayed, requiresVehicle: true, includedAccessories: ['2 micrófonos inalámbricos', 'Soportes para los micrófonos inalámbricos', 'Trípode firme de altura regulable', 'Cable de alimentación'], sellerConfirmedFields: ['description', 'condition', 'conditionNotes', 'includedAccessories'], research: SOURCES.speaker }),
  item(49, { title: 'Rack metálico para ollas y sartenes', category: 'Cocina', description: 'Rack metálico de cocina para colgar ollas y sartenes. Incluye exactamente 6 ganchos tipo S asociados a este rack. Las ollas y sartenes que aparecen en las fotos no están incluidas.', condition: 'Usado', conditionNotes: 'El vendedor confirma que se vende la rejilla metálica negra con sus 6 ganchos tipo S.', knownDefects: 'Sin defectos relevantes informados; herrajes de instalación a confirmar durante la revisión.', photos: ['IMG_7778.JPG'], asking: 220000, marketLow: 160000, marketHigh: 320000, fast: 180000, floor: 150000, confidence: 'Media', ...immediate, includedAccessories: ['6 ganchos tipo S'], sellerConfirmedFields: ['title', 'description', 'conditionNotes', 'knownDefects', 'includedAccessories'], research: SOURCES.general }),
  item(50, { title: 'Biblioteca alta de madera', category: 'Muebles', description: 'Biblioteca alta de madera con varios estantes abiertos.', condition: 'Buen estado visual', conditionNotes: 'Estructura sin daños evidentes en la foto.', knownDefects: 'Medidas y estabilidad a confirmar.', photos: ['IMG_7780.JPG'], asking: 500000, marketLow: 400000, marketHigh: 750000, fast: 430000, floor: 360000, confidence: 'Media', ...delayed, requiresVehicle: true, requiresLoadingHelp: true, research: SOURCES.furniture }),
  item(51, { title: 'Escritorio compacto para computadora', category: 'Oficina', description: 'Escritorio compacto de madera con bandeja para teclado, estante inferior y ruedas. Los objetos apoyados o visibles alrededor no están incluidos.', condition: 'Usado', conditionNotes: 'Presenta desgaste leve propio del uso.', knownDefects: 'Deslizamiento de bandeja, ruedas y medidas a confirmar.', photos: ['IMG_7781.JPG'], asking: 250000, marketLow: 200000, marketHigh: 350000, fast: 220000, floor: 180000, confidence: 'Media', ...delayed, requiresVehicle: true, research: SOURCES.desk }),
  item(52, { title: 'Paraguas azul a cuadros', category: 'Hogar', description: 'Paraguas azul a cuadros con mango recto metálico, vendido de forma individual. El paraguas bordó que también aparece debajo en la foto no está incluido en este artículo.', condition: 'Usado', conditionNotes: 'La foto lo muestra abierto; tela y varillas sin roturas evidentes.', knownDefects: 'Mecanismo de apertura a confirmar durante la revisión individual.', photos: ['IMG_7685.JPG'], asking: 50000, marketLow: 35000, marketHigh: 80000, fast: 40000, floor: 30000, confidence: 'Media', ...immediate, research: SOURCES.general }),
  item(53, { title: 'Mesita simple de madera', category: 'Muebles', description: 'Mesita muy sencilla de madera. Las plantas y macetas que aparecen en la foto no están incluidas; se venden por separado.', condition: 'Usado', conditionNotes: 'Precio confirmado directamente por el vendedor. Acabado rústico con desgaste visible y pintura clara en la superficie.', knownDefects: 'Medidas y estabilidad a confirmar durante la revisión.', photos: ['IMG_7725-table.JPG'], asking: 10000, marketLow: 150000, marketHigh: 350000, fast: 10000, floor: 10000, confidence: 'Precio del vendedor', ...immediate, requiresVehicle: false, sellerConfirmedFields: ['title', 'description', 'askingPricePYG', 'recommendedFastSalePricePYG', 'adminPriceFloorPYG', 'requiresVehicle'], research: `${SOURCES.table} | HISTÓRICO: investigación anterior conservada. SELLER_CONFIRMED: precio pedido Gs. 10.000; no elevar automáticamente.` }),
];
