import type { AdminProduct } from './types';

export const SAMPLE_PRODUCTS: AdminProduct[] = [
  {
    id: 'demo-fridge-01', itemNumber: null, slug: 'heladera-inverter-420l', title: 'Heladera inverter 420 L',
    category: 'Electrodomésticos', tags: ['heladera', 'cocina', 'inverter'],
    description: 'Heladera amplia con freezer inferior, ideal para una familia. Este artículo es un ejemplo para validar la reserva con retiro posterior.',
    condition: 'Muy buen estado', conditionNotes: 'Funciona correctamente y se entrega limpia.', knownDefects: 'Pequeña marca superficial en un lateral.',
    images: ['https://images.unsplash.com/photo-1554871920-9d1295c3dfe4?auto=format&fit=crop&w=1000&h=760&q=82'],
    askingPricePYG: 3000000, originalPricePYG: 3250000, saleMode: 'DELAYED', pickupAvailableDate: '2026-12-07', pickupWindowStart: null, pickupWindowEnd: null, depositPercent: 25,
    requiresVehicle: true, requiresLoadingHelp: true, logisticsNotes: ['Traer vehículo adecuado', 'Traer ayuda para cargar', 'Traer mantas o correas', 'Artículo pesado'], includedAccessories: [],
    status: 'AVAILABLE', featured: true, dateListed: '2026-08-26', lastPriceChange: '2026-08-27', isDemo: true, needsReview: false,
    adminPriceFloorPYG: 2400000, marketEstimatePYG: 3350000, recommendedFastSalePricePYG: 2750000, pricingConfidence: 'Media',
    pricingResearch: 'Datos de demostración; sin investigación de mercado real.', internalNotes: 'DEMO DATA · Seguir usando hasta diciembre.', holdExpiresAt: null,
  },
  {
    id: 'demo-washer-01', itemNumber: null, slug: 'lavarropas-frontal-9kg', title: 'Lavarropas frontal 9 kg',
    category: 'Electrodomésticos', tags: ['lavarropas', 'lavandería', 'hogar'],
    description: 'Lavarropas frontal de buena capacidad. Ejemplo de artículo que sigue en uso hasta pocos días antes de la mudanza.',
    condition: 'Buen estado', conditionNotes: 'Todos los programas principales funcionan.', knownDefects: 'Desgaste normal en la bandeja del jabón.',
    images: ['https://images.unsplash.com/photo-1655041448985-f6666cba2d6c?auto=format&fit=crop&w=1000&h=760&q=82'],
    askingPricePYG: 2100000, originalPricePYG: null, saleMode: 'DELAYED', pickupAvailableDate: '2026-12-09', pickupWindowStart: null, pickupWindowEnd: null, depositPercent: 25,
    requiresVehicle: true, requiresLoadingHelp: true, logisticsNotes: ['Traer vehículo adecuado', 'Traer ayuda para cargar', 'Artículo pesado'], includedAccessories: [],
    status: 'AVAILABLE', featured: false, dateListed: '2026-08-25', lastPriceChange: null, isDemo: true, needsReview: false,
    adminPriceFloorPYG: 1700000, marketEstimatePYG: 2300000, recommendedFastSalePricePYG: 1950000, pricingConfidence: 'Baja',
    pricingResearch: 'Datos de demostración; sin investigación de mercado real.', internalNotes: 'DEMO DATA · Confirmar mangueras al importar inventario real.', holdExpiresAt: null,
  },
  {
    id: 'demo-tv-01', itemNumber: null, slug: 'smart-tv-50-pulgadas', title: 'Smart TV 50 pulgadas',
    category: 'Electrónica', tags: ['televisor', 'smart tv', 'sala'],
    description: 'Televisor inteligente con control remoto. Ejemplo de compra inmediata con pago completo para garantizar el artículo.',
    condition: 'Muy buen estado', conditionNotes: 'Pantalla sin rayas; control incluido.', knownDefects: 'Sin defectos conocidos.',
    images: ['https://images.unsplash.com/photo-1679840861056-75a41a01fe88?auto=format&fit=crop&w=1000&h=760&q=82'],
    askingPricePYG: 1850000, originalPricePYG: 2050000, saleMode: 'IMMEDIATE', pickupAvailableDate: null, pickupWindowStart: null, pickupWindowEnd: null, depositPercent: 100,
    requiresVehicle: false, requiresLoadingHelp: false, logisticsNotes: ['Artículo frágil', 'Traer manta para proteger la pantalla'], includedAccessories: [],
    status: 'AVAILABLE', featured: true, dateListed: '2026-08-27', lastPriceChange: '2026-08-28', isDemo: true, needsReview: false,
    adminPriceFloorPYG: 1450000, marketEstimatePYG: 2100000, recommendedFastSalePricePYG: 1700000, pricingConfidence: 'Media',
    pricingResearch: 'Datos de demostración; sin investigación de mercado real.', internalNotes: 'DEMO DATA · Probar ejemplo de pago completo.', holdExpiresAt: null,
  },
  {
    id: 'demo-chair-01', itemNumber: null, slug: 'silla-oficina-ergonomica', title: 'Silla de oficina ergonómica',
    category: 'Oficina', tags: ['silla', 'oficina', 'escritorio'],
    description: 'Silla regulable con apoyo lumbar y ruedas. Lista para retiro una vez confirmado el pago.',
    condition: 'Muy buen estado', conditionNotes: 'Elevación y ruedas funcionando.', knownDefects: 'Leve desgaste en un apoyabrazos.',
    images: ['https://kanademono.design/cdn/shop/products/KanademonoLiftingSwivelDeskChairAllblack_Imagecut_01_1080x.jpg?v=1656639940'],
    askingPricePYG: 620000, originalPricePYG: null, saleMode: 'IMMEDIATE', pickupAvailableDate: null, pickupWindowStart: null, pickupWindowEnd: null, depositPercent: 100,
    requiresVehicle: false, requiresLoadingHelp: false, logisticsNotes: ['Puede requerir desmontaje'], includedAccessories: [],
    status: 'AVAILABLE', featured: true, dateListed: '2026-08-26', lastPriceChange: null, isDemo: true, needsReview: false,
    adminPriceFloorPYG: 480000, marketEstimatePYG: 700000, recommendedFastSalePricePYG: 560000, pricingConfidence: 'Baja',
    pricingResearch: 'Datos de demostración; sin investigación de mercado real.', internalNotes: 'DEMO DATA.', holdExpiresAt: null,
  },
  {
    id: 'demo-table-01', itemNumber: null, slug: 'mesa-comedor-seis-personas', title: 'Mesa de comedor para 6',
    category: 'Muebles', tags: ['mesa', 'comedor', 'madera'],
    description: 'Mesa de madera para seis personas. Se reserva con seña porque sigue en uso hasta diciembre.',
    condition: 'Buen estado', conditionNotes: 'Estructura firme.', knownDefects: 'Marcas leves de uso en la superficie.',
    images: ['https://images.unsplash.com/photo-1605885795793-097ffaee6b7c?auto=format&fit=crop&w=1000&h=760&q=82'],
    askingPricePYG: 1400000, originalPricePYG: null, saleMode: 'DELAYED', pickupAvailableDate: '2026-12-06', pickupWindowStart: null, pickupWindowEnd: null, depositPercent: 25,
    requiresVehicle: true, requiresLoadingHelp: true, logisticsNotes: ['Traer vehículo adecuado', 'Traer ayuda para cargar', 'Puede requerir desmontaje'], includedAccessories: [],
    status: 'AVAILABLE', featured: true, dateListed: '2026-08-24', lastPriceChange: null, isDemo: true, needsReview: false,
    adminPriceFloorPYG: 1050000, marketEstimatePYG: 1550000, recommendedFastSalePricePYG: 1250000, pricingConfidence: 'Media',
    pricingResearch: 'Datos de demostración; sin investigación de mercado real.', internalNotes: 'DEMO DATA · Medir puertas al cargar.', holdExpiresAt: null,
  },
  {
    id: 'demo-coffee-01', itemNumber: null, slug: 'cafetera-de-filtro', title: 'Cafetera de filtro',
    category: 'Cocina', tags: ['cafetera', 'café', 'cocina'],
    description: 'Cafetera compacta con jarra de vidrio, lista para retirar después de confirmar el pago.',
    condition: 'Buen estado', conditionNotes: 'Calienta y filtra correctamente.', knownDefects: 'La jarra tiene pequeñas marcas de uso.',
    images: ['https://images.unsplash.com/photo-1674504866626-fe4f19f68564?auto=format&fit=crop&w=1000&h=760&q=82'],
    askingPricePYG: 300000, originalPricePYG: 360000, saleMode: 'IMMEDIATE', pickupAvailableDate: null, pickupWindowStart: null, pickupWindowEnd: null, depositPercent: 100,
    requiresVehicle: false, requiresLoadingHelp: false, logisticsNotes: ['Artículo frágil'], includedAccessories: [],
    status: 'AVAILABLE', featured: false, dateListed: '2026-08-28', lastPriceChange: '2026-08-28', isDemo: true, needsReview: false,
    adminPriceFloorPYG: 220000, marketEstimatePYG: 350000, recommendedFastSalePricePYG: 275000, pricingConfidence: 'Media',
    pricingResearch: 'Datos de demostración; sin investigación de mercado real.', internalNotes: 'DEMO DATA.', holdExpiresAt: null,
  },
  {
    id: 'demo-tools-01', itemNumber: null, slug: 'juego-herramientas-basicas', title: 'Juego de herramientas básicas',
    category: 'Herramientas', tags: ['herramientas', 'lote', 'reparación', 'bundle'],
    description: 'Lote de herramientas manuales para arreglos domésticos. Sirve también como ejemplo de producto tipo bundle.',
    condition: 'Usado, funcional', conditionNotes: 'Piezas con desgaste normal de uso.', knownDefects: 'El estuche no cierra perfectamente.',
    images: ['https://images.unsplash.com/photo-1575839127400-6b9e36bf97f8?auto=format&fit=crop&w=1000&h=760&q=82'],
    askingPricePYG: 280000, originalPricePYG: null, saleMode: 'IMMEDIATE', pickupAvailableDate: null, pickupWindowStart: null, pickupWindowEnd: null, depositPercent: 100,
    requiresVehicle: false, requiresLoadingHelp: false, logisticsNotes: ['Se entrega como lote completo'], includedAccessories: [],
    status: 'AVAILABLE', featured: false, dateListed: '2026-08-23', lastPriceChange: null, isDemo: true, needsReview: false,
    adminPriceFloorPYG: 200000, marketEstimatePYG: 320000, recommendedFastSalePricePYG: 250000, pricingConfidence: 'Baja',
    pricingResearch: 'Datos de demostración; sin investigación de mercado real.', internalNotes: 'DEMO DATA · Revisar inventario del lote antes de publicar en fase real.', holdExpiresAt: null,
  },
  {
    id: 'demo-decor-01', itemNumber: null, slug: 'jarron-ceramica-artesanal', title: 'Jarrón de cerámica artesanal',
    category: 'Decoración', tags: ['jarrón', 'cerámica', 'decoración'],
    description: 'Pieza decorativa de cerámica en tono natural. Disponible para retiro inmediato después del pago.',
    condition: 'Excelente estado', conditionNotes: 'Sin roturas ni reparaciones.', knownDefects: 'Sin defectos conocidos.',
    images: ['https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?auto=format&fit=crop&w=1000&h=760&q=82'],
    askingPricePYG: 180000, originalPricePYG: null, saleMode: 'IMMEDIATE', pickupAvailableDate: null, pickupWindowStart: null, pickupWindowEnd: null, depositPercent: 100,
    requiresVehicle: false, requiresLoadingHelp: false, logisticsNotes: ['Artículo frágil'], includedAccessories: [],
    status: 'AVAILABLE', featured: false, dateListed: '2026-08-28', lastPriceChange: null, isDemo: true, needsReview: false,
    adminPriceFloorPYG: 130000, marketEstimatePYG: 220000, recommendedFastSalePricePYG: 165000, pricingConfidence: 'Baja',
    pricingResearch: 'Datos de demostración; sin investigación de mercado real.', internalNotes: 'DEMO DATA.', holdExpiresAt: null,
  },
];
